### ISSUE TITLE
Plans for Blender 2.8.x ?

### ISSUE THREAD

**Issue by RBBlackstone** [EVERTims/game_engine_evertims#3]
I get the "update to 2.8x required" when installed.

Do you have plans for 2.8 compatibility in v0.3?

I don't know how I could help, but I would be happy to try.

**Comment by PyrApple** [comment]
Yes plans for a 2.8 update, as part of a complete rebuild of the framework. Sources not public yet though, thanks for the proposition.

**Comment by RBBlackstone** [comment]
Awesome!!!
